### ISSUE TITLE
Weld BOM has wrong scope

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/liberty-arquillian#11]
A recent PR introduced
```
    <!-- WELD classes, these are present in FFDC 
         and are sometimes instances of TCK @ShouldThrow exceptions -->
    <dependency>
      <groupId>org.jboss.weld</groupId>
      <artifactId>weld-core-bom</artifactId>
      <version>3.0.4.Final</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
```
the liberty-managed/pom.xml

I believe this code DOES have the needed effect (in that it enables the load of a
WELD Exception class that is the subclass of a ShouldThrow) but the bom should
only be in a dependancyManagement section of a pom. So I need to do some
more maven learning (e.g. http://www.baeldung.com/spring-maven-bom ) and in the meantime
move/change the dependancy.

CT pointed out that this is flagged up by maven as a bad scope.

This warning normally shoots off the top of my terminal unnoticed:
```
[WARNING] Some problems were encountered while building the effective model for io.openliberty.arquillian:arquillian-liberty-managed:jar:1.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.scope' for org.jboss.weld:weld-core-bom:pom must be one of [provided, compile, runtime, test, system] but is 'import'. @ io.openliberty.arquillian:arquillian-liberty-managed:[unknown-version], /Users/hutchig/git/liberty-arquillian/liberty-managed/pom.xml, line 209, column 14
```

**Comment by chyt** [comment]
Closed by #12.

**Comment by hutchig** [comment]
If you search for bom at https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/pom.xml  that folder is definately not going to have subprojects and has been seen by lots
or experienced people and is in the dependancyManagement section.

**Comment by chyt** [comment]
I think the convention is to put `bom`s in the `dependencyManagement` section since they are generally meant to unify versions between subprojects. For our purposes, putting the bom in `dependencies` as a `pom` type dependency also works since we don't have any subprojects.

I'm not sure which way is more correct for our situation. I don't think it matters that much. I just suggested keeping it under `dependencies` since I thought creating a new section would clutter the pom unnecessarily.
