### ISSUE TITLE
Arquillian: Add support for Jakarta EE 9

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/liberty-arquillian#71]
In doing early testing with the new Jakarta EE9-compatible versions of the CDI and Bean Validation TCKs, I've discovered that we need an updated version of liberty-arquillian to support running with EE9 technologies.

At a minimum, I've found the following so far:
- Update relevant javax package references to jakarta.
- Support Arquillian 1.7 and arquillian-protocol-servlet-jakarta by deploying applications to the new ArquillianServletRunnerEE9 URI.
- Note: There will not be a version of the j2eeManagement feature compatible with EE9, so those code paths will not be used in an EE9 environment.

**Comment by Azquelt** [comment]
If we can no longer rely on the j2eeManagement feature, we will need to find another way of getting information about the servlets which are deployed (doesn't have to be something from jakarta, just has to work on liberty in conjunction with EE9 features).

There are test cases which demonstrate what doesn't work when j2eeManagement is not present here: https://github.com/OpenLiberty/liberty-arquillian/tree/master/liberty-managed/src/test/java/io/openliberty/arquillian/managed/needsmanagementmbeans

It's mostly injection of URLs of servlets when multiple apps are deployed. I'm pretty sure we had to add it because there was a TCK test which depended on being able to do this.

**Comment by yeekangc** [comment]
@ericglau

**Comment by kathrynkodama** [comment]
UFO: https://ibm.box.com/s/fnnj1ot0gwvd7jilxk6mgjgs96ao9uw8

**Comment by kathrynkodama** [comment]
The design document has been updated to clarify the new major version release associated with this epic. See slide 15: https://ibm.box.com/s/fnnj1ot0gwvd7jilxk6mgjgs96ao9uw8

The changes are as follows:
- the new `2.0.0` major release of Liberty Arquillian will use new artifact ids with a "jakarta" suffix: `arquillian-liberty-managed-jakarta`, `arquillian-liberty-remote-jakarta`, `arquillian-liberty-support-jakarta`
- any maintenance to the `1.x` release will continue to be published under the existing artifact id, ex. `arquillian-liberty-managed`
- the corresponding Liberty Arquillian Dependencies bundles will be updated to match the new artifact ids: `arquillian-liberty-managed-jakarta-junit`, `arquillian-liberty-managed-jakarta-testng`, `arquililan-liberty-remote-jakarta-junit`, `arquillian-liberty-remote-jakarta-testng`

**Comment by hantsy** [comment]
Hope it is aligned with JUnit 5, as I know,  Arquillian 1.7.0.Alpha5 added JUnit 5 support.

I have updated my sample codes, and test Arquillian 1.7, JUnit 5, Arquillian Glassfish Container for GF v6, https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/40

**Comment by kathrynkodama** [comment]
Thank you @hantsy, we will be updating to Arquillian `1.7.0.Alpha5` which will align us with JUnit 5 and the Jakarta `Servlet 5.0` protocol.

**Comment by hantsy** [comment]
@kathrynkodama I am trying to update my Jakarta EE 9 starter sample and [adding liberty aruqillian](https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/54) back. But I encountered an issue with Rest API testing, I can not find a public CXF for the Jakarta EE 9, I am not sure if OpenLiberty(Jakarta ee 9) is still using CXF as the JaxRS implementation.

[In the former Jakarta EE 8 version](https://github.com/hantsy/jakartaee8-starter/blob/master/pom.xml#L1174),  I added  CXF JaxRS deps in the test classpath to make it work.

**Comment by kathrynkodama** [comment]
@hantsy 

I noticed in your `it-with-arq-liberty-managed` a feature definition could not be found for `localConnector-1.0`. Currently, the `localConnector-1.0` feature is not included in the Open Liberty Jakarta EE 9 beta package. 
If you use the all beta features package: https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/2020-11-11_0736/openliberty-21.0.0.1-beta.zip the `localConnector-1.0` feature should be resolved.

As for the JAX-RS failures, I believe it may be because JAX-RS is not yet included in the Open Liberty Jakarta EE 9 beta features:
https://openliberty.io/blog/2020/11/24/microprofile-rest-client-kubernetes-secrets-21001beta.html#jakarta

**Comment by hantsy** [comment]
@kathrynkodama Thanks.
1. Switch to use artifactId `openliberty-runtime` in the *arq-liberty-managed* profile.
2. OpenLiberty 21.0.0.0.beta should include Jaxrs, but I looked in the *restulWS-xxx.mf*, and the jars in the *lib* folder, and found the following jars.

```
io.openliberty.org.jboss.resteasy.common.jakarta_1.0.47.jar
io.openliberty.org.jboss.resteasy.jaxb.provider.jakarta_1.0.47.jar
io.openliberty.org.jboss.resteasy.server.jakarta_1.0.47.jar
```

It seems in this Jakarta EE 9 version, it switched to **Resteasy**.

**Comment by hantsy** [comment]
@kathrynkodama Use **jersey** Jaxrs client to get the tests passed. https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/54

**Comment by brideck** [comment]
@kathrynkodama With the release of 2.0.0, is this issue ready to be closed?  Or is there more that needs to happen?

**Comment by kathrynkodama** [comment]
@brideck With the release of 2.0.0, we can now close this issue. Thank you.
